# Imported PKI lab servers (generated by Terraform import, then cleaned up)
# Changes from generated output:
#   - Removed primary_network_interface blocks (conflict with private_ip / associate_public_ip_address)
#   - Removed ipv6_address_count / ipv6_addresses (conflicting empty defaults)
#   - Added lifecycle { prevent_destroy = true } to every server

resource "aws_instance" "dc" {
  ami                                  = "ami-031283482dcfced88"
  associate_public_ip_address          = true
  availability_zone                    = "us-east-1c"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = true
  force_destroy                        = false
  get_password_data                    = false
  hibernation                          = false
  instance_initiated_shutdown_behavior = "stop"
  instance_type                        = "t3.medium"
  key_name                             = "RachitTest"
  monitoring                           = false
  placement_partition_number           = 0
  private_ip                           = "172.31.68.1"
  region                               = "us-east-1"
  secondary_private_ips                = []
  security_groups                      = ["RachitDefault"]
  source_dest_check                    = true
  subnet_id                            = "subnet-689c110d"
  tags = {
    Name = "PKI_ngco_pro_rac_DC"
  }
  tags_all = {
    Name = "PKI_ngco_pro_rac_DC"
  }
  tenancy                     = "default"
  user_data                   = null
  user_data_replace_on_change = null
  volume_tags                 = null
  vpc_security_group_ids      = ["sg-0cd1ef25ec2944cff"]
  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }
  cpu_options {
    core_count       = 1
    threads_per_core = 2
  }
  credit_specification {
    cpu_credits = "unlimited"
  }
  enclave_options {
    enabled = false
  }
  maintenance_options {
    auto_recovery = "default"
  }
  metadata_options {
    http_endpoint               = "enabled"
    http_protocol_ipv6          = "disabled"
    http_put_response_hop_limit = 2
    http_tokens                 = "required"
    instance_metadata_tags      = "disabled"
  }
  private_dns_name_options {
    enable_resource_name_dns_a_record    = true
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }
  root_block_device {
    delete_on_termination = true
    encrypted             = false
    iops                  = 3000
    tags                  = {}
    tags_all              = {}
    throughput            = 125
    volume_size           = 30
    volume_type           = "gp3"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_instance" "tpp" {
  ami                                  = "ami-06f6b7ecb36846008"
  associate_public_ip_address          = true
  availability_zone                    = "us-east-1b"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = true
  force_destroy                        = false
  get_password_data                    = false
  hibernation                          = false
  instance_initiated_shutdown_behavior = "stop"
  instance_type                        = "t3.xlarge"
  key_name                             = "RachitTest"
  monitoring                           = false
  placement_partition_number           = 0
  private_ip                           = "172.31.30.125"
  region                               = "us-east-1"
  secondary_private_ips                = []
  security_groups                      = ["RachitDefault"]
  source_dest_check                    = true
  subnet_id                            = "subnet-a69c16ff"
  tags = {
    Name = "PKI_Rachit_Ngco_TPP"
  }
  tags_all = {
    Name = "PKI_Rachit_Ngco_TPP"
  }
  tenancy                     = "default"
  user_data                   = null
  user_data_replace_on_change = null
  volume_tags                 = null
  vpc_security_group_ids      = ["sg-0cd1ef25ec2944cff"]
  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }
  cpu_options {
    core_count       = 2
    threads_per_core = 2
  }
  credit_specification {
    cpu_credits = "unlimited"
  }
  enclave_options {
    enabled = false
  }
  maintenance_options {
    auto_recovery = "default"
  }
  metadata_options {
    http_endpoint               = "enabled"
    http_protocol_ipv6          = "disabled"
    http_put_response_hop_limit = 2
    http_tokens                 = "required"
    instance_metadata_tags      = "disabled"
  }
  private_dns_name_options {
    enable_resource_name_dns_a_record    = true
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }
  root_block_device {
    delete_on_termination = true
    encrypted             = false
    iops                  = 3000
    tags                  = {}
    tags_all              = {}
    throughput            = 125
    volume_size           = 75
    volume_type           = "gp3"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_instance" "vsatellite" {
  ami                                  = "ami-0f2425d4cce4e97dd"
  associate_public_ip_address          = true
  availability_zone                    = "us-east-1a"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = false
  force_destroy                        = false
  get_password_data                    = false
  hibernation                          = false
  instance_initiated_shutdown_behavior = "stop"
  instance_type                        = "t2.medium"
  key_name                             = "RachitTest"
  monitoring                           = false
  placement_partition_number           = 0
  private_ip                           = "172.31.5.194"
  region                               = "us-east-1"
  secondary_private_ips                = []
  security_groups                      = ["RachitDefault"]
  source_dest_check                    = true
  subnet_id                            = "subnet-e5d7a392"
  tags = {
    Name = "PKI_Rac_Vsatellite"
  }
  tags_all = {
    Name = "PKI_Rac_Vsatellite"
  }
  tenancy                     = "default"
  user_data                   = null
  user_data_replace_on_change = null
  volume_tags                 = null
  vpc_security_group_ids      = ["sg-0cd1ef25ec2944cff"]
  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }
  cpu_options {
    core_count       = 2
    threads_per_core = 1
  }
  credit_specification {
    cpu_credits = "standard"
  }
  enclave_options {
    enabled = false
  }
  maintenance_options {
    auto_recovery = "default"
  }
  metadata_options {
    http_endpoint               = "enabled"
    http_protocol_ipv6          = "disabled"
    http_put_response_hop_limit = 1
    http_tokens                 = "optional"
    instance_metadata_tags      = "disabled"
  }
  private_dns_name_options {
    enable_resource_name_dns_a_record    = true
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }
  root_block_device {
    delete_on_termination = true
    encrypted             = false
    iops                  = 100
    tags                  = {}
    tags_all              = {}
    throughput            = 0
    volume_size           = 20
    volume_type           = "gp2"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_instance" "adcs" {
  ami                                  = "ami-01a15dfc48279bf55"
  availability_zone                    = "us-east-1a"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = true
  force_destroy                        = false
  get_password_data                    = false
  hibernation                          = false
  instance_initiated_shutdown_behavior = "stop"
  instance_type                        = "t3.large"
  key_name                             = "RachitTest"
  monitoring                           = false
  placement_partition_number           = 0
  private_ip                           = "172.31.13.33"
  region                               = "us-east-1"
  secondary_private_ips                = []
  security_groups                      = ["RachitDefault"]
  source_dest_check                    = true
  subnet_id                            = "subnet-e5d7a392"
  tags = {
    Name = "PKI_NGCO_ADCS"
  }
  tags_all = {
    Name = "PKI_NGCO_ADCS"
  }
  tenancy                     = "default"
  user_data                   = null
  user_data_replace_on_change = null
  volume_tags                 = null
  vpc_security_group_ids      = ["sg-0cd1ef25ec2944cff"]
  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }
  cpu_options {
    core_count       = 1
    threads_per_core = 2
  }
  credit_specification {
    cpu_credits = "unlimited"
  }
  enclave_options {
    enabled = false
  }
  maintenance_options {
    auto_recovery = "default"
  }
  metadata_options {
    http_endpoint               = "enabled"
    http_protocol_ipv6          = "disabled"
    http_put_response_hop_limit = 2
    http_tokens                 = "required"
    instance_metadata_tags      = "disabled"
  }
  private_dns_name_options {
    enable_resource_name_dns_a_record    = true
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }
  root_block_device {
    delete_on_termination = true
    encrypted             = false
    iops                  = 3000
    tags                  = {}
    tags_all              = {}
    throughput            = 125
    volume_size           = 30
    volume_type           = "gp3"
  }

  lifecycle {
    prevent_destroy = true
  }
}
